//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
//

import AWSCore
import AWSMobileHubHelper
import AWSCognitoIdentityProvider


/// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_YWiyB9cSt"

/// Cognito User ID
let AWSCognitoID: String = "us-east-1:d0d2cc0d-a727-4228-91b7-f1e7aba06e5c"

/// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "4aosg5oj8fcqiv20uf1mic1sds"

/// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .usEast1

/// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "i1v063lb331rq6f8r8jc9fldtomfv3ooqglpjupkng2isa8apq7"

/// Identifier for Cloud Logic API invocation clients
let AWSCloudLogicDefaultConfigurationKey: String = "CloudLogicAPIKey"
let AWSCloudLogicDefaultRegion: AWSRegionType = .usEast1


/// Pool that contains users for authentification
let pool = AWSCognitoIdentityUserPool(forKey: AWSCognitoUserPoolsSignInProviderKey)

let idManager = AWSCognitoIdentityProvider(forKey: "USEast1CognitoIdentityProvider")

let ONE_SIGNAL_APP_ID = "60f1a2ad-082f-4ff0-9d51-dbf991bc23f3"



