//
//  Users.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
import Foundation
import UIKit
import AWSDynamoDB

class Users: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _username: String?
    var _bio: String?
    var _birthday: NSNumber?
    var _company: String?
    var _dateCreated: NSNumber?
    var _email: String?
    var _firstname: String?
    var _gender: String?
    var _instagramID: String?
    var _isPrivate: NSNumber?
    var _isVerified: NSNumber?
    var _lastname: String?
    var _location: Set<NSNumber>?
    var _middlename: String?
    var _phonenumber: String?
    var _pinterestID: String?
    var _points: NSNumber?
    var _profilePictureUrl: String?
    var _redditID: String?
    var _soundcloudID: String?
    var _spotifyID: String?
    var _githubID: String?
    var _swapCodeUrl: String?
    var _swapped: NSNumber?
    var _swaps: NSNumber?
    var _twitterID: String?
    var _vineID: String?
    var _vimeoID: String?
    var _website: String?
    var _willShareEmail: NSNumber?
    var _willShareInstagram: NSNumber?
    var _willSharePhone: NSNumber?
    var _willSharePinterest: NSNumber?
    var _willShareReddit: NSNumber?
    var _willShareSoundCloud: NSNumber?
    var _willShareSpotify: NSNumber?
    var _willShareTwitter: NSNumber?
    var _willShareVine: NSNumber?
    var _willShareYouTube: NSNumber?
    var _willShareGitHub: NSNumber?
    var _willShareVimeo: NSNumber?
    var _youtubeID: String?
    var _notification_id_one_signal: String?
    var _VPCode: String?
    
    class func dynamoDBTableName() -> String {
        
        return "swap-mobilehub-1081613436-Users"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_username"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_username" : "username",
            "_bio" : "bio",
            "_birthday" : "birthday",
            "_company" : "company",
            "_dateCreated" : "date_created",
            "_email" : "email",
            "_firstname" : "firstname",
            "_gender" : "gender",
            "_instagramID" : "instagram_ID",
            "_isPrivate" : "isPrivate",
            "_isVerified" : "isVerified",
            "_lastname" : "lastname",
            "_location" : "location",
            "_middlename" : "middlename",
            "_phonenumber" : "phonenumber",
            "_pinterestID" : "pinterest_ID",
            "_points" : "points",
            "_profilePictureUrl" : "profile_picture_url",
            "_redditID" : "redditID",
            "_githubID": "githubID",
            "_soundcloudID" : "soundcloud_ID",
            "_spotifyID" : "spotify_ID",
            "_swapCodeUrl" : "swap_code_url",
            "_swapped" : "swapped",
            "_swaps" : "swaps",
            "_twitterID" : "twitter_ID",
            "_vineID" : "vine_ID",
            "_vimeoID": "vimeoID",
            "_website" : "website",
            "_willShareEmail" : "willShareEmail",
            "_willShareInstagram" : "willShareInstagram",
            "_willSharePhone" : "willSharePhone",
            "_willSharePinterest" : "willSharePinterest",
            "_willShareReddit" : "willShareReddit",
            "_willShareSoundCloud" : "willShareSoundCloud",
            "_willShareSpotify" : "willShareSpotify",
            "_willShareTwitter" : "willShareTwitter",
            "_willShareVine" : "willShareVine",
            "_willShareYouTube" : "willShareYouTube",
            "_willShareGitHub": "willShareGitHub",
            "_willShareVimeo": "willShareVimeo",
            "_youtubeID" : "youtube_ID",
            "_notification_id_one_signal": "notification_id_one_signal",
            "_VPCode": "VPCode"
        ]
    }
}
